### ISSUE TITLE
Want to add debian10

### ISSUE THREAD

**Issue by wnctrunk** [Virtual-Machines/Lubuntu-VirtualBox#3]
Very nice base system:)  Thank you for creating such an excellent project. Hope to add Debian 10 for more options！

**Comment by DavidGarciaPrados** [comment]
> Very nice base system:) Thank you for creating such an excellent project. Hope to add Debian 10 for more options！

I have created a Debian 10 machine. Enjoy!
https://github.com/Virtual-Machines/Debian-VirtualBox
